### ISSUE TITLE
Mechanism Characterization

### ISSUE THREAD

**Issue by gjurgiel** [rambunction4330/RobotCode2022#101]
We need to calculate the feedforward and PID constants for all the mechanisms so that we can use the fancy code we have been working on. After we have the constants we can start writing/testing commands and subsystems.

- [x] Drivetrain
- [x] Intake (spinner optional)
- [x] Turret
- [x] Hood
- [x] Flywheel

**Comment by abheekda1** [comment]
Why isn't Aiden assigned this.

**Comment by gjurgiel** [comment]
I forgot to

**Comment by abheekda1** [comment]
I know :)

**Comment by theVerySharpFlat** [comment]
[04b8170](https://github.com/rambunction4330/RobotCode2022/pull/98/commits/04b8170c8acbbda24428b00e81f60b6a49ee05d0) updated the constants. @gcjurgiel could you make sure I did it correctly

**Comment by theVerySharpFlat** [comment]
mechanical added weight to the turret. need to recalculate the PID and FF values

**Comment by notSam25** [comment]
> I forgot to

you forgor 💀

**Comment by theVerySharpFlat** [comment]
I broke the flywheel trying to get feedforward values :(

**Comment by theVerySharpFlat** [comment]
We did the hood

**Comment by theVerySharpFlat** [comment]
@gcjurgiel we did the drivetrain today right?

**Comment by gjurgiel** [comment]
Yes!
