### ISSUE TITLE
FIX YOUR COMMIT MESSAGES

### ISSUE THREAD

**Issue by ADawesomeguy** [rambunction4330/RobotCode2022#108]
They're not making sense.

**Comment by ADawesomeguy** [comment]
`fix` - Aiden
`merge` - Sam

yall disappoint me

**Comment by theVerySharpFlat** [comment]
@ADawesomeguy could you please provide us with more info? Where are these commits of mine?

**Comment by ADawesomeguy** [comment]
Literally the first commit in https://github.com/rambunction4330/RobotCode2022/pull/98

**Comment by theVerySharpFlat** [comment]
I think I may have been spiting Josh Rosen

**Comment by ADawesomeguy** [comment]
Bruv you gotta step up your game.

**Comment by theVerySharpFlat** [comment]
In spiting people or writing commit messages?

**Comment by ADawesomeguy** [comment]
Both

**Comment by notSam25** [comment]
idc about your stupid git names. I named my commits after what Aiden told me to. Sugma

**Comment by theVerySharpFlat** [comment]
> idc about your stupid git names. I named my commits after what Aiden told me to. Sugma

Why blame on me? 

I think the thing these days is to shoot an insult back at the attacker.

Well

You know how we count your attendance? The amount of soda that we have in the fridge.

![MXB](https://user-images.githubusercontent.com/74067227/155639581-51c16840-0422-4157-b600-e3f966982b68.gif)

So take that.

**Comment by ADawesomeguy** [comment]
Gotem

**Comment by notSam25** [comment]
Thats it, im not giving anyone anymore shmuchks offbrand soda. because of Aiden's smol brain nobody gets anymore.

**Comment by notSam25** [comment]
rip bozo

**Comment by theVerySharpFlat** [comment]
> rip bozo

well you are stupid head too :(

**Comment by theVerySharpFlat** [comment]
gay pride

**Comment by theVerySharpFlat** [comment]
I hate them gayz
