### ISSUE TITLE
Gearbox issue on the turret

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#109]
This is a mechanical issue. When I tried to move the motor, it made squeaking noises and didn't budge. I think mechanical is on it.

**Comment by gjurgiel** [comment]
Sounds like the motor shaft came disconnected from the gear box again. It's been a recurring issue. Try to decrease the max velocity and acceleration to put less stress on it next time. When you use smart motion it will go to the max velocity with the max acceleration, so if those are too high the motor might be breaking itself by accelerating too quickly to too fast a speed.

**Comment by theVerySharpFlat** [comment]
I see. The motor broke at half speed though,

**Comment by notSam25** [comment]
jolly good

**Comment by gjurgiel** [comment]
They fixed it
