### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by abheekda1** [rambunction4330/RobotCode2022#14]
I haven't taken a look over the license for wpilib so I'm not sure what kind of licenses we can use as a subset of that but I feel we should keep it open-source with one of these options:
- [ ] GNU GPL 3.0
- [ ] Apache 2.0
- [x] MIT

Let me know what you guys think.

Edit: After reading the license provided by WPILib it seems that it may be best to define a separate license for our code and a separate one for the pre-provided WPILib code (which would be the license already in the repo.)

**Comment by gjurgiel** [comment]
Looking at [this forum post](https://www.chiefdelphi.com/t/best-license-under-which-to-publish-code/158498), I think that this is probably a good idea. I have no idea which license is best or the differences between them, but I lean toward MIT since I tend to see it used more.

**Comment by abheekda1** [comment]
They're relatively similar and all very open. MIT is basically a simpler version of Apache-2.0 without nuances and GPL 3.0 allows the usage of the code but requires that the license of any forks or software that uses the code to be open (meaning that one can't take the code and make proprietary software with it). Apache and MIT are the same except they allow proprietary forks. I agree that MIT seems like the right decision here.

**Comment by gjurgiel** [comment]
Great! I added one to main.
