### ISSUE TITLE
Get rid of SparkMaxVelocityController<U>::SparkMaxVelocityController(int deviceID) constructor

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#41]
This constructor is not needed. I will get rid of it. This is a note to self.

**Comment by theVerySharpFlat** [comment]
@ADawesomeguy I am having trouble getting rid of these constructors as the DriveSubsystem uses these constructors. You won't be able to switch to the other constructor until Sam pushes the changes on his computer, but after that, could you please use the better constructor? 

Thanks,
Aiden

**Comment by abheekda1** [comment]
I'll give it a shot, yep.

**Comment by notSam25** [comment]
ok boomer

**Comment by abheekda1** [comment]
@theVerySharpFlat now that it's merged should I be able to use the new constructor?
