### ISSUE TITLE
Doxygen Workflow on PRs

### ISSUE THREAD

**Issue by abheekda1** [rambunction4330/RobotCode2022#48]
It seems the workflow builds the page even for PRs to main, so I think we have a couple options:
1. We can allow these because it keeps the #47 PR constantly building
2. We can get rid of it and test the build at the very end
3. We can change the workflow to only build on doxygen branch commits

**Comment by abheekda1** [comment]
Seems to be working as it's only building pushes to `doxygen`. Closing.

**Comment by theVerySharpFlat** [comment]
I feel like it should be building the documentation from the main branch not the doxygen branch as "main" is the official branch with the official code.

**Comment by abheekda1** [comment]
Well right now all the commits are going to the doxygen branch, so I was thinking it should follow that now and then once we merge the PR it'll follow the main branch.

**Comment by theVerySharpFlat** [comment]
That makes sense. Thanks for the clarification!
