### ISSUE TITLE
Simple Drive

### ISSUE THREAD

**Issue by gjurgiel** [rambunction4330/RobotCode2022#59]
Not for this repository, but I wanted to put it somewhere. We need to just make a simple joystick drive for driver testing on Saturday. Just keep it locally on the driverStation laptop from a cpp/TimedRobot template and use the frc::MecanumDrive and frc::Joystick classes for simplicity.

**Comment by theVerySharpFlat** [comment]
@gcjurgiel did we do this today?

**Comment by gjurgiel** [comment]
Yes! We did it in the first five minutes.
