### ISSUE TITLE
Pancakes

### ISSUE THREAD

**Issue by EnigmaAlliance** [rambunction4330/RobotCode2022#76]
1 ½ cups all-purpose flour 
3 ½ teaspoons baking powder
¼ teaspoon salt, or more to taste
1 tablespoon white sugar
1 ¼ cups milk
1 egg 
3 tablespoons butter, melted
ADD ALL INGREDIENTS TO SHOPPING LIST 
Local Offers
ZIP 63044

Walmart
11900 Saint Charles Rock Rd
BRIDGETON, MO 63044

Great Value Organic All Purpose Flour
Stock up for winter. Everyday Low Prices.

ADVERTISEMENT

Marketside Organic Cage Free Brown Eggs, Large, 12 Ct
Stock up for winter. Everyday Low Prices.

ADVERTISEMENT

•
Buy Ingredients

Walmart Logo
7 ingredients
$17.09
DirectionsInstructions Checklist
Step 1
In a large bowl, sift together the flour, baking powder, salt and sugar. Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.

Step 2
Heat a lightly oiled griddle or frying pan over medium-high heat. Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.

**Comment by abheekda1** [comment]
Adding this to docs now, thanks for the issue!

**Comment by abheekda1** [comment]
Working well, will push soon:
![image](https://user-images.githubusercontent.com/67982792/152228910-78fdd751-100d-49c1-bee4-b5e400cb3bc1.png)

**Comment by abheekda1** [comment]
> Walmart Logo

**Comment by theVerySharpFlat** [comment]
??/???//?

**Comment by theVerySharpFlat** [comment]
:)
