### ISSUE TITLE
The issue with the position controller

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#80]
@gcjurgiel !!!!!!!!!!! I think the issue with the position controller isn't an issue with the actual postion controller code! I think its because we didn't account for the gear ratio from the motor to the wheel. Thus, when we told it to go to position 2.x it was going to position 2.x, just on the motor and not the wheel, which is why the wheel didn't spin all the way around/

**Comment by abheekda1** [comment]
deep.

**Comment by gjurgiel** [comment]
I think your right! It's so annoying that it's always such a small error causing all our pain.

**Comment by theVerySharpFlat** [comment]
and now we can't even fix it. All of the code is sitting on the laptop at school

**Comment by abheekda1** [comment]
You should always push smh. Btw would this be fixed with passing a gear ratio parameter or something?

**Comment by gjurgiel** [comment]
You'd fix it by making the conversion factor `3_in / 12_rad` instead of `3_in / 1_rad`.

**Comment by gjurgiel** [comment]
it's literally a one character difference

**Comment by abheekda1** [comment]
Vivimos en un sociedad.

**Comment by theVerySharpFlat** [comment]
No, es una problema economica

**Comment by theVerySharpFlat** [comment]
¡necesitamos mas dinero!

**Comment by theVerySharpFlat** [comment]
We need to resolve merge issues on the linked pull request so we can close this issue.

**Comment by gjurgiel** [comment]
I already did, merged, and deleted the branch.

**Comment by abheekda1** [comment]
Bruh Aiden be slackin. I bet he forgot to `git pull` 🤓

**Comment by theVerySharpFlat** [comment]
We need to update `motto.md` for my stupidity
