### ISSUE TITLE
Velocity controllers status.

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#81]
Are we done with SparkMaxVelocityController? If so, I would like to move the task in projects to "done".

**Comment by theVerySharpFlat** [comment]
Also, are we done with feedforwards?

**Comment by gjurgiel** [comment]
Yes, except for talons

**Comment by theVerySharpFlat** [comment]
Ok, moved all the SparkMaxVelocity stuff into "done"
