### ISSUE TITLE
NavX odometry

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#82]
Looking for things to do while we are confined to remote development. And, in general, things that we still need to get done.

**Comment by gjurgiel** [comment]
Here are a few things that you might be able to do:

- Setting up subsystems and commands (Specifically storage, shooter, and climber)
- Setting up the RobotContainer class
- Accelerometer odometry using the navX?
- Implementing ballistic trajectories in code (I've already done the math)
- Helping me with vision.
- Unfinished talon motor controller classes
- Documenting

Let me know what sounds most interesting so I can give you more specific details, or anything else you van think of in case I'm missing something.

**Comment by theVerySharpFlat** [comment]
Vision sounds cool, but I think we have more important things to work on. I might look into the accelerometer odometry thing using the navX. It's going to be a lot of math, but I think it will be worth it.

**Comment by theVerySharpFlat** [comment]
How soon are we going to get a robot with the subsystems that you mentioned? Don't we only have two weeks to test that code? Scary

**Comment by gjurgiel** [comment]
>It's going to be a lot of math

look at [this](https://www.kauailabs.com/public_files/navx-mxp/apidocs/c++/class_a_h_r_s.html#aae2d8d97068bb168c41346532593f626) it might not be

**Comment by gjurgiel** [comment]
The two week limit is a little loose though. We will have up until after spring break to actually get the robot working. I know Jiya doesn't want to be meeting that whole time, and I can't blame her.  It's a long time, and there will be nothing for anyone besides programming to do. We will have seminars though, and I can probably get us more after school meetings if we need it. I'm not too worried... yet.

**Comment by theVerySharpFlat** [comment]
Wow.

Our hands are being held. So are our feet. We're getting frickin carried.

**Comment by theVerySharpFlat** [comment]
> I'm not too worried... yet.

- @gcjurgiel 2022

**Comment by theVerySharpFlat** [comment]
thanks George. Here's a big salute for all you do:
![](https://www.emojirequest.com/images/SalutingEmoji.jpg)

**Comment by gjurgiel** [comment]
Accelerometer odometry might not even be worth pursuing though, looking at [this](https://pdocs.kauailabs.com/navx-mxp/wp-content/uploads/2019/02/navx-mxp_robotics_navigation_sensor_user_guide.pdf) (pg. 7).

**Comment by gjurgiel** [comment]
Though [newer versions](https://pdocs.kauailabs.com/navx-mxp/wp-content/uploads/2021/02/navx2-mxp_robotics_navigation_sensor_user_guide-9.pdf) (same page) are more accurate, but I'm not sure which we have.

**Comment by gjurgiel** [comment]
But the mecum encoders aren't all that great either, so it's worth testing

**Comment by theVerySharpFlat** [comment]
Wait, so they didn't use the navx for odometry?

**Comment by theVerySharpFlat** [comment]
Also, the displacement functions are experimental and the docs say that they are innacurate.

**Comment by gjurgiel** [comment]
They are. It cites ±1 meter over the 15 second auto, which is quite bad. If it interests you, it would be nice to experiment with it, but it likely won't be better than the encoder odometry so it's not a high priority. (Another place we could get odometry from is vision, but that is a hard problem. We likely don't have time for this season unless someone wants to devote a *lot* of time and learning to it)

**Comment by theVerySharpFlat** [comment]
It even says that it's getVelocity functions are not accurate. Theoretically, they could (perhaps) obtain (maybe) better results with the UpdateDisplacement function if they used an integration method other than the basic method of approximating the area of rectangles under the acceleration curve as they do here:

https://github.com/kauailabs/navxmxp/blob/5e010ba810bb7f7eaab597e0b708e34f159984db/roborio/c%2B%2B/navx_frc_cpp/src/InertialDataIntegrator.cpp#L14-L33

You can see that all they do is basically multiply acceleration by Δt<sup>2</sup> and add it to position.

Theoretically, with previous datapoints, we could implement a more accurate method to calculating position using one of the [newton-cotes formulas](https://en.wikipedia.org/wiki/Newton%E2%80%93Cotes_formulas), however this would involve using their poorly documented callback system in order to run this at a rate that would minimize error as much as possible (as close to 200HZ as possible). This being said, assuming we are using their rawAcceleration values (which do not account for acceleration due to gravity, although I'm not sure whether or not it applies to us on a 2D plane), we need to integrate twice and there is bound to be error accumulation. Another thing is consistency of the position updating. If we do not update the position at a constant time, the newton-cotes formulas will not behave properly, since they assume evenly-spaced datapoints. 

Odometry sounds cool, but do we really need it? Can't we just say

```
if ROBOT_SEE_BALL
    goToBall()
    collectBall()
    orientToTarget()
    shootBall()
```

or something?

The only thing I'm kind of scared about is the part where we have to find the hangar. Do we need odometry for that?

**Comment by gjurgiel** [comment]
Odometry is useful for autonomously driving a single trajectory, not long term position tracking. Trajectories works similarly to a  profiledPID controller (for position). It needs a feedback position and velocity and odometry acts as that feedback. Following trajectories is not necessary for auto, but it can allow us to do more complex things during auto. 

But, after those 15 seconds odometry is mostly useless since human drivers can just see here the robot is. In past years it might have been beneficial to run trajectories during the teleop phase for better alignment, but it doesn't seem that way this year. We already have a good enough form of odometry implemented using encoders, so a new odometry system is not needed (although I do find it cool).

We will not need to autonomously find the hanger.
