### ISSUE TITLE
Teleop Turning

### ISSUE THREAD

**Issue by gjurgiel** [rambunction4330/RobotCode2022#89]
I have no idea why, but when I use theses kinematics values it works. I copied them from something else I did, and I'm not sure what is different about them (besides the small nudge in value), but it does make it turn.
```
const frc::Translation2d frontLeftPose  = { 0.303_m, -0.299_m},
                         frontRightPose = { 0.303_m,  0.299_m}, 
                         rearLeftPose   = {-0.303_m, -0.299_m},
                         rearRightPose  = {-0.303_m,  0.299_m,};
```

**Comment by abheekda1** [comment]
Yay! I wonder if the values are modified in some other way and making them equal in magnitude (although different in sign) is what makes them sort of balance each other out.

**Comment by abheekda1** [comment]
I'll update this locally tomorrow and PR to main for the command system setup.
