### ISSUE TITLE
🚨 🚨 🚨 URGENT ---> BUILD FAILING 🚨 🚨 🚨 

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#90]
It seems like pull request #88 was not made sure to pass checks before it was merged. Now the main repo is one giant **BUILD FAILED**. I blame @ADawesomeguy.

**Comment by theVerySharpFlat** [comment]
see [motto.md](https://github.com/rambunction4330/RobotCode2022/blob/main/motto.md)

**Comment by theVerySharpFlat** [comment]
<img src="https://c.tenor.com/kwKqvc4Kug8AAAAC/beedo-minions.gif"/>

**Comment by abheekda1** [comment]
It's because Sam needed the RobotContainer.h file so I pushed it but it seems there were also a couple files on my local machine that needed to be pushed for a successful build, which I will do *later* so please stfu.

**Comment by theVerySharpFlat** [comment]
This is still an issue.

**Comment by theVerySharpFlat** [comment]
> please stfu.

ouch

**Comment by abheekda1** [comment]
Ok we can resolve it once I make the PR having to do with #89. tbf though it builds on my machine.

**Comment by abheekda1** [comment]
ily \<3
