### ISSUE TITLE
Documentation of subsystems

### ISSUE THREAD

**Issue by theVerySharpFlat** [rambunction4330/RobotCode2022#95]
@ADawesomeguy is it possible to configure doxygen to document the robot code also? It would also be great if you could make it seperate from the Robot Library documentation.

**Comment by abheekda1** [comment]
I can give it a shot.

**Comment by theVerySharpFlat** [comment]
Thanks! Documentation would be really helpful (after the episode with Sam's code yesterday)

**Comment by abheekda1** [comment]
Episode? It was a whole damn season.

**Comment by notSam25** [comment]
shutup you smell, I told you I would clean it up if I had the time(was busy doin' your mom)

**Comment by abheekda1** [comment]
There was nothing to clean up, only burn.

**Comment by theVerySharpFlat** [comment]
@ADawesomeguy how is this going

**Comment by abheekda1** [comment]
I'll get to work on it next week, Ima be out of town this weekend.

**Comment by theVerySharpFlat** [comment]
what a slacker. cancel vacation

**Comment by abheekda1** [comment]
it was not vacation, i'll do this at school tomorrow.

**Comment by notSam25** [comment]
> it was not vacation, i'll do this at school tomorrow.

imagine attending school... could be me. :(

**Comment by abheekda1** [comment]
Oh I should do this

**Comment by notSam25** [comment]
Yeah we are never doing this.

**Comment by abheekda1** [comment]
So true. Next year:tm:.
